//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User32
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arenda
    {
        public string passport { get; set; }
        public string transport_ID { get; set; }
        public System.DateTime date { get; set; }
        public string duration { get; set; }
        public string status { get; set; }
        public string comm { get; set; }
        public int manager_ID { get; set; }
        public int ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
