//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User32
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport()
        {
            this.Arenda = new HashSet<Arenda>();
        }
    
        public string ID { get; set; }
        public int mark_ID { get; set; }
        public int model_ID { get; set; }
        public int color_ID { get; set; }
        public string cuzov { get; set; }
        public string transmission { get; set; }
        public int doors { get; set; }
        public string @class { get; set; }
        public string gas { get; set; }
        public int year { get; set; }
        public decimal run { get; set; }
        public decimal prize_all { get; set; }
        public decimal prize_hour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arenda> Arenda { get; set; }
        public virtual Color Color { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Model Model { get; set; }
    }
}
